version: "3.9"
services:
  minio:
    image: minio/minio
    restart: always
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    #      - '9001:9001'
    #    networks:
    #      - minionetwork
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:13.3
    restart: always
    container_name: postgres_db2
    environment:
      POSTGRES_DB: storage_db
      POSTGRES_USER: saha
      POSTGRES_PASSWORD: saha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  minio_data:
  redis_data:
  #networks:
  #  minionetwork:


