version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: always
    container_name: postgres_db2
    environment:
      POSTGRES_DB: storage_db
      POSTGRES_USER: saha
      POSTGRES_PASSWORD: saha
    ports:
      - "5432:5432"
    volumes:
          - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'
